### PR TITLE
Prefixes in alignment graphs

### PR DESCRIPTION
**Pull request by dr-shorthair**
Very minor tweak to help this alignment graph play nice - update prefixes to match the ones used elsewhere

### CODE REVIEW

**Review by lewismc — APPROVED** [review]
+1

**Review by brandonnodnarb — APPROVED** [review]
sweet.

**Comment by carueda** [comment]
@dr-shorthair I just noted this review request ... sorry, I won't be able to review for the time being.  Since I'm noting 3 reviewers now and that 3 reviews are required for merge, may I ask you to consider other possible extra reviewers?

**Comment by dr-shorthair** [comment]
@carueda it's a small change - just making namespace prefixes consistent with the new convention. But I've asked (the indefatigable) @smrgeoinfo so it is not left on the stack unnecessarily ;-)

**Pull request merged**
