### PR TITLE
updated ns for .../reprSpaceCoordinate to "sorepscd"

### PR DESCRIPTION
**Pull request by brandonnodnarb**
line 219; 
was a ns collision with ../reprSciComponent -- line 211

### CODE REVIEW

**Comment by brandonnodnarb** [comment]
Can someone verify there's no typos in this change.  It looks good to me...

I tagged you @lewismc, but @anyone can verify.

**Comment by dr-shorthair** [comment]
Is the intention to go back into all the .ttl files and swap the (external) prefixes to these stadard ones as well? Inside https://github.com/ESIPFed/sweet/blob/master/src/reprSpaceCoordinate.ttl I see
```
@prefix : <http://sweetontology.net/reprSpaceCoordinate/> .
@prefix dir: <http://sweetontology.net/propSpaceDirection/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix repr: <http://sweetontology.net/repr/> .
@prefix sdir: <http://sweetontology.net/reprSpaceDirection/> .
@prefix coord: <http://sweetontology.net/reprSpaceCoordinate/> .
@prefix srela: <http://sweetontology.net/relaSpace/> .
@prefix srela2: <http://sweetontology.net/relaSpace/> .
```

**Comment by lewismc** [comment]
@dr-shorthair 

> Is the intention to go back into all the .ttl files and swap the (external) prefixes to these stadard ones as well?

Yes. I acknowledge that this is going to take time but I think that's OK. We never formalized it before... now we have and individual files should reflect that now.

**Comment by lewismc** [comment]
Well caught @brandonnodnarb I merged. Thanks.

**Pull request merged**
