### PR TITLE
ISSUE-6 URI transition and governance

### PR DESCRIPTION
**Pull request by lewismc**
Hi @ESIPFed/semtech this pull request addresses #6 
Next steps is to have redirects setup from sweetontology.net to an ontology server or the live OWL files for SWEET. We need to discuss this.
I suppose we should also set up redirects for all other SWEET suffixes to sweetontology.net

### CODE REVIEW

**Comment by carueda** [comment]
Hi @lewismc, @dr-shorthair 

Per this comment in particular https://github.com/ESIPFed/sweet/issues/6#issuecomment-306365351, I fully agree about not including any version in the IRIs of the ontologies. Moreover, I strongly suggest not even including the `.owl` extension either.  You can still keep the files themselves with the `.owl` extension, but do not include it in the IRIs.

**Comment by dr-shorthair** [comment]
+1 from me to omitting any suffix that looks like a file-type extension. 
I know it could be argued that .owl just lets you know that it is an OWL ontology, but 
(i) other formalizations might be used in the future under the same name
(ii) it is not compatible with all RDF/OWL IDEs (TopBraid objects)

I have no problem with there being an artefact with the .owl extension, probably denoting the OWL/XML serialization, alongside .rdf, .json-ld, .ttl, .nt etc, but the canonical identifier for the ontology should not have .owl at the end.

**Comment by lewismc** [comment]
Hi @dr-shorthair @carueda thank you for the input, I've updated the URIs.

@dr-shorthair let's address your canonical manifestation issue within a separate issue to keep things clean.

**Comment by lewismc** [comment]
Hi @dr-shorthair @carueda thank you for the input, I've updated the URIs.

@dr-shorthair let's address your canonical manifestation issue within a separate issue to keep things clean.

**Comment by lewismc** [comment]
Thank you for review @dr-shorthair @carueda

**Comment by dr-shorthair** [comment]
BTW - I'm not sure that there needs to be a 'canonical' representation for publication (see my comment on #26). But I would advocate using Turtle for the dev version - all the tools support it now, and it is easiest for eyeballing and for manipulation in a text-editor. 

(FWIW discussions of RDF canonicalization usually end up with n-triples, because they can be sorted easily so diffs can be done reliably.)

**Comment by carueda** [comment]
Agree. 
Turtle/N3 would be much more convenient/readable for humans.
N-triples not as much, but it's amenable for diffs.

BTW.  I think no specific discussion/conclusion has been done re actual hosting of the ontologies. My point is that, a system like the ORR could take care of the various serializations on top of the base/source one (say Turtle). This is just a quick general comment.  It may be perfectly fine to capture all desired representations at build time and use some apache config to take care of the content negotiation, etc.

**Pull request merged**
