### PR TITLE
ISSUE-47 Avoid prov: prefix

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses #47

### CODE REVIEW

**Comment by lewismc** [comment]
@stain can you please scope this out and provide your input?
Also, please suggest, if you wish, for how you would like your ORCID to be associated with the contribution.

**Comment by stain** [comment]
+1 `sciprov` looks like a good fix for the namespace prefix, go for it. I've added it to http://prefix.cc/sciprov

I don't know how you track ORCID attributions - your [issue template](https://github.com/ESIPFed/sweet/blob/master/issue_template.md) listed that, so I guess just being in #47 is sufficient?

**Comment by lewismc** [comment]
Thank you @stain 
Anyone else?

**Comment by dr-shorthair** [comment]
OK by me

**Comment by carueda** [comment]
LOTM

**Pull request merged**
