### PR TITLE
changed spelling of gulley to gully

### PR DESCRIPTION
**Pull request by brandonnodnarb**
NOTE: did *not* change URI

### CODE REVIEW

**Comment by lewismc** [comment]
I think that this Class should be marked as deprecated. See https://github.com/ESIPFed/sweet/blob/master/src/matrMineral.ttl#L104-L109 as an example.

**Comment by brandonnodnarb** [comment]
Updated as per request.  Do we need three reviewers for these?

**Review by dr-shorthair — APPROVED** [review]

**Review by lewismc — APPROVED** [review]
+1

**Comment by lewismc** [comment]
@graybeal can you please review?

**Pull request merged**
