### PR TITLE
Changed axiom AquaticEcosystem hasRealm ONLY Ocean to AquaticEcosystem hasRealm ONLY Hydrosphere

### LINKED ISSUE #94: problem axiom: AquaticEcosystem SubClassOf hasRealm some Ocean
The semantics of OWL dictate that this means every instance of AquaticEcosystem bears a hasRealm relationship to some instance of Ocean. But this is not true: aquatic ecosystems can be freshwater

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #94

### CODE REVIEW

**Comment by smrgeoinfo** [comment]
The change certainly make sense from a science point of view, but from an ontology engineering point of view, it changes the semantics of AquaticEcosystem, and there should be a new URI to identify the updated concept, shouldn't there?  If the URI's have a version token, this could be incremented.

**Comment by cmungall** [comment]
Hi @smrgeoinfo, based on the conversation here: #49 the feeling was there was low semantic drift and that URIs should remain stable. But maybe we should open a new ticket to handle versioning in particular.

FWIW, in numeric fragment schemes like OBO, we deprecate and mint a new URI if the definition changes, perhaps migrating the label across. But for minor changes in axioms the URI is preserved.

Hopefully some kind of agreement about this can be reached, otherwise it will be hard to evolve the content in SWEET!

**Comment by smrgeoinfo** [comment]
As long as we can safely assume that no one is using SWEET URI's to get associated OWL restrictions used for any kind of inferencing, then the same URI would work; if this is indeed the case, it would make a lot more sense to me to not include ANY OWL restrictions in SWEET and put those kind of connotations/denotations for the loosey-goosey SWEET concepts in something like a skos:definition or rdf:Description

**Comment by graybeal** [comment]
Well, this is debated, but I think the general practice is not to issue a new IRI just because a concept's properties have been changed.  Big picture, because semantics are often changed as the ontology matures, and it would repeatedly obsolete any ongoing application of the ontology, as relied-upon IRIs become deprecated.  From a meta-physical or philosophical or something-like-that view, the _concept_ is invariant, even if we have not accurately described it previously. This is complicated slightly by the fact SWEET concepts have a thin anchor to their 'actual meaning', see third paragraph.

Does this mean someone who has counted on it to mean thing X may be impacted when we say it does not mean thing X?  Yes.  But this cuts both ways. Some of those people (or their computer systems) may have used that relationship to understand the meaning of the concept, and been misled for all these years. They will finally have a system that works the way it *should*.  But others would consider the change to have affected things in an unhelpful way, if they really wanted the previous meaning. 

Two observations about SWEET that make me lean even further toward "just change the relationship": It provided very few relationships, so it isn't like there's a complex model that people have been relying on (and verifying, and looking to as an anchor for the meaning). And it provides almost no definitions, so there is no human-centric way to anchor a concept either, except for the label itself.  (Well, and a third thing too: I don't think it is _heavily_ used by other systems yet. But I'd love to hear differently on that score.)

**Comment by lewismc** [comment]
@smrgeoinfo I think versioning IRI's is an important but different conversation... honestly IMHO it is one which would block any real development elsewhere right now. It is also one for which we have quite a bit of consensus building to do. Thank you for raising it.

**Comment by cmungall** [comment]
Seems the the PR is good to merge?

**Comment by whitten** [comment]
So since you broadened Ocean into Hydrosphere, 
would it make sense to add an axiom that said an Ocean is a subcategory of the Hydrosphere ?
Also that the axiom using MarineEcosystem tied to Ocean is also appropriate in SWEET ?

For my knowledge, it seems that the axiom tying MarineEcosystem to Ocean and this axiom tying EquaticEcosystem to Hydrosphere are related in some way.  What would this relation be called ?

**Comment by pbuttigieg** [comment]
Terse notes : An ocean is part of a hydrosphere. Not all marine ecosystems
are oceans or parts thereof.

Some ENVO URIs for comparison :
Hydrosphere http://purl.obolibrary.org/obo/ENVO_01000819

Aquatic environment http://purl.obolibrary.org/obo/ENVO_01000317

Ocean http://purl.obolibrary.org/obo/ENVO_00000015

**Comment by lewismc** [comment]
@cmungall any comments based upon @whitten and @pbuttigieg ?

**Comment by cmungall** [comment]
I think the PR is still good. Following on from what @whitten says, it would be good to have what we call a design pattern linking X-EcoSystem to X-Realms (perhaps even definitional axioms). But this could be done as a separate piece of work

**Comment by lewismc** [comment]
+1 @cmungall do you have merge permissions? If not we can grant you.

**Comment by cmungall** [comment]
I do not

**Comment by lewismc** [comment]
@cmungall @pbuttigieg I've granted you both write permissions to the repository. Apologies I thought you both had it previously. 
Thank you @cmungall for the contribution.

**Pull request merged**
