### PR TITLE
ISSUE-125 Use wikidata to provide skos:definition to owl:Class'es

### PR DESCRIPTION
**Pull request by lewismc**
This pull request supersedes #203 

@graybeal regarding the definitions. I simply removed the `skos:definition`'s for those ones.

There was only one entry which required a `skos:historyNote` this is as follows
```
###  http://sweetontology.net/phenCryo/GlacierRetreat
:GlacierRetreat rdf:type owl:Class ;
                rdfs:subClassOf :GlacialProcess ,
                                <http://sweetontology.net/phenSystem/Retreat> ,
                                <http://sweetontology.net/procStateChange/Melting> ;
                rdfs:label "glacier retreat"@en ;
                rdfs:seeAlso <https://github.com/ESIPFed/sweet/issues/185> ;
                skos:closeMatch <http://purl.obolibrary.org/obo/ENVO_01001656> ;
                skos:definition _:genid5 ,
                                _:genid6 .

_:genid5 dcterms:created "2020-04-09T10:20:12-08:00Z"^^xsd:dateTimeStamp ;
          dcterms:creator <https://orcid.org/0000-0003-4091-6059> ;
          dcterms:source <https://orcid.org/0000-0003-4808-4736> ;
          rdfs:comment "The process of glacier ice loss."@en ;
          <http://www.w3.org/ns/prov#wasDerivedFrom> <http://purl.obolibrary.org/obo/ENVO_01001656> ;
          skos:historyNote "Native curated definition by ESIP Semantic Harmonization Committee."@en .

_:genid6 dcterms:created "2020-07-20T17:20:42.890"^^xsd:dateTime ;
          dcterms:creator <https://orcid.org/0000-0003-2185-928X> ;
          dcterms:source <http://www.wikidata.org/entity/Q94706497> ;
          rdfs:comment "shrinking of a glacier"@en ;
```

Finally, @graybeal @brandonnodnarb @rrovetto see the [requested generated CSV file](https://docs.google.com/spreadsheets/d/1NLtlAecaSlAOVy5_1_IQraORaKemnWNhxF0UXHbB44M/edit?usp=sharing).

### CODE REVIEW

**Comment by lewismc** [comment]
There appear to be some files which are failing to write... I am investigating those right now. Also, I noticed that a few other files are failing due to host connection timeout issues... this may have to do with OWLAPI or the host or the process... I am not sure.

**Comment by lewismc** [comment]
Carried over from #203 from @dr-shorthair 

> Attempting to load in TopBraid so I can run the SPARQL: a lot of errors from mis-formatted xsd"dateTime and xsd:dateTimeStamp :-( in phenCryo and realmCryo ...

**Comment by lewismc** [comment]
@dr-shorthair right now the annotation looks as follows
```
_:genid1 dcterms:created "2020-07-20T17:03:26.420"^^xsd:dateTime ;
```
... what should the value be instead?

**Comment by brandonnodnarb** [comment]
Yes, but realmCryo was last edited 2 months ago...

**Comment by brandonnodnarb** [comment]
Looking at the spreadsheet (many thanks @lewismc) it looks like abbreviations are matching to genetic elements.  For example, [sic](https://github.com/lewismc/sweet/blob/9182a0dfcb98da835e8e6765f9fbfe261fb92c1f/src/propCategorical.ttl#L147), which is an equivalent class to [Standard Industrial Classification](https://github.com/lewismc/sweet/blob/9182a0dfcb98da835e8e6765f9fbfe261fb92c1f/src/propCategorical.ttl#L159) (and, IMHO, should probably be a `skos:altLabel`), is finding a wikidata match as `"genetic element in the species Drosophila melanogaster"@en`

It looks like any definition starting with "genetic element in the species..."  can probably be disregarded.

**Comment by lewismc** [comment]
@brandonnodnarb thanks for taking a look. Regarding abbreviations yes I am +1 for adding clarifying axioms as you suggest. This is a bit difficult ti implement automatically though... I don't know how I would do that. 

> It looks like any definition starting with "genetic element in the species..." can probably be disregarded.

I can implement this check pretty easily. I'll go ahead and do that. Essentially, it just means that these definitions will be dropped.

**Comment by dr-shorthair** [comment]
I got a bunch of reports where 
- there was a trailing 'Z' after a time-zone offset - it is one or the other, not both! 
- there were some with spaces embedded - but I can't find them now. 

TB might be finding some stuff in imports, but diagnostics a bit lacking.

**Comment by lewismc** [comment]
@dr-shorthair 

> there was a trailing 'Z' after a time-zone offset - it is one or the other, not both!

I think this is a bug and should be addressed in a separate pull request. Are you able to submit that one?

> there were some with spaces embedded - but I can't find them now.

OK, I've not experienced this one!

**Comment by rrovetto** [comment]
> Protege 5.5 doesn't throw an error, but the definition shows as blank brackets in the editor.  

Likewise--it also only displayed blank brackets when I tried.

**Comment by brandonnodnarb** [comment]
> Regarding abbreviations yes I am +1 for adding clarifying axioms as you suggest. This is a bit difficult ti implement automatically though... I don't know how I would do that.

Apologies, this ^ was snark -- I have mentioned this [before](https://github.com/ESIPFed/sweet/issues/118) but haven't had time to address it.  (I need a sarcasm font.)  I think I can write a simple filter for to extract the subsets.

Anwyay.  Assuming #207 fixes the time stamp issue(s), I think this is good to go.  There are definitely some definitions that don't seem correct, but they aren't obviously wrong --- aside from the "genetic element" defs.   

Assuming nothing else breaks, I think it's a good start. :)

**Comment by smrgeoinfo** [comment]
incorrect mapping of geologic time intervals (from the csv dump)


_sweet:stateTime/Age | age | http://www.wikidata.org/entity/Q185836 | "period of life of a human   or organism"@en |_ 
should map to **https://www.wikidata.org/wiki/Q568683**

_sweet:stateTime/Epoch | epoch | http://www.wikidata.org/entity/P6259 | "epoch of an astronomical   object coordinate"@en_
should map to | **https://www.wikidata.org/wiki/Q754897**

_sweet:stateTime/Period | period | http://www.wikidata.org/entity/Q101843 | "row in the periodic table   of elements"@en_
should map to  **https://www.wikidata.org/wiki/Q392928**

**Comment by smrgeoinfo** [comment]
lots of other incorrect mappings, particularly for commonly used words, some examples:

- Bottom:  "role in a BDSM relationship"@en
- Rim:  "The external flange that is machined, cast, molded, stamped or pressed around the bottom of a firearms cartridge"
- Flank: "side of the body between the rib cage and the iliac bone of the hip"
- Margin "a type of financial collateral used to cover credit risk"
- Validated : "badge being used as a Wikisource work status indicator"
- Shell: ""in solid mechanics" [didn't get all the text???]
- Layer: "in electronics, a single thickness of some material covering a surface"

**Comment by lewismc** [comment]
@brandonnodnarb no problems ;)

Great @smrgeoinfo some comments from you

> sweet:stateTime/Age | age | http://www.wikidata.org/entity/Q185836 | "period of life of a human or organism"@en |
should map to https://www.wikidata.org/wiki/Q568683
... I will update these manually in the next iteration. 

> lots of other incorrect mappings, particularly for commonly used words, some examples... problem defs are highlighted in yellow.

I'll go ahead and manually remove these incorrect annotations. We can address them in future work.

**Pull request closed without merging**
