### PR TITLE
Added UCUM codes in `skos:notation` properties

### LINKED ISSUE #237: [ALIGNMENT] reprSciUnits to UCUM
Add UCUM symbols to reprSciUnits

Propose to add them using `skos:notation` using the datatype `qudt:UCUMcs` from http://qudt.org/2.1/schema/qudt

### PR DESCRIPTION
**Pull request by dr-shorthair**
Added UCUM codes to provide consistent keys for alignment efforts
Fixes #237

### CODE REVIEW

**Review by smrgeoinfo — CHANGES_REQUESTED** [review]
Looks like a very useful  addition.  Good trick using the qudt:UCUMcs as a data type for an rdf literal.  Adds http://purl.org/dc/terms/license and  http://www.w3.org/2004/02/skos/core#notation as owl:AnnotationProperty, this shouldn't be a problem-- the full namespaces are not imported.  

The owl:versionInfo property on the ontology is not  updated in the revised version, it seems to have disappeared-- should be added back and updated. Maybe v3.6.0-- this changes are backward compatible but add functionality. Not just a bug fix.

**Comment by dr-shorthair** [comment]
Thanks @smrgeoinfo - version (and contributor) metadata reinstated.

**Review by smrgeoinfo — APPROVED** [review]
Simon update with version and contributor. Looks good to go.

**Review by lewismc — APPROVED** [review]
+1 @dr-shorthair sterling effort.

**Review by brandonnodnarb — APPROVED** [review]
>  Good trick using the qudt:UCUMcs as a data type for an rdf literal.

+1

Nice one @dr-shorthair  (and apologies for taking so long to review)

**Pull request merged**
