### PR TITLE
ISSUE-27 Alignment with SOSA/SSN

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses #27

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Yeah - lack of textual definitions in SWEET makes it hard to judge. 
Certainly the sosa:Sensor is intended to relate to any kind of value-estimation procedure, including simulations, interpretations (sensing with the mind and education ...) and forecasts, as well as classical physical sensors.

**Comment by graybeal** [comment]
matr is for 'matter', right?  so, only a subset of the sosa (which addresses any kind of sensor, including computational), not equivalent class.

(Right?)

**Comment by lewismc** [comment]
ACK @graybeal I will update

**Comment by lewismc** [comment]
@graybeal updated to accommodate your suggestion.

**Comment by lewismc** [comment]
@ESIPFed/semtech @dr-shorthair @carueda @graybeal @kjano any comments on the current state of this PR? 
It is a small initial contribution. The bulk of this alignment is being worked over at #41

**Comment by graybeal** [comment]
In the absence of any description of the task, it is impossible to comment on its current state. 

I would be very pleasantly surprised if a complete alignment was possible without major effort, so I am comfortable declaring small victories.

**Comment by lewismc** [comment]
@graybeal thanks for comments.

> In the absence of any description of the task, it is impossible to comment on its current state.

The task is described at #27 this is a starting point for alignment. The major work is starting over at #41 so your comments would be very much appreciated over there as well.
Does anyone have objection to merging this pull request and shifting main development for SOSA/SSN alignment to #41 ?
Thanks

**Comment by graybeal** [comment]
sorry, never realized this was a pull request (thinking PR was problem report, doh!). Only concern is the one mentioned elsewhere, namely when you should and shouldn't bring mappings into the core ontology. If you're using them as a means to define and constrain the meaning of the concept, it makes sense — but you have to be sure the statements in the other ontology (sosa in this case) don't cause breakage. 

As long as that's in mind, I have no issue with doing the merge and continuing elsewhere.

**Pull request merged**
