### PR TITLE
ISSUE-20 added rdfs:label property to everything with a URI

### PR DESCRIPTION
**Pull request by brandonnodnarb**

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @brandonnodnarb this is pretty monumental :)

I hope to high hell that you didn't do this manually...

Lets discuss this a bit further...

I know you, like me, are not particularly fond of taking wikipedia/dbpedia prefLabels and applying them to every URI. I did however recently talk to Nick Juty (if you can find and tag him it would be great) and he mentioned he was really looking for better labels.

This is a great start no doubt about it, thanks for commenting on the above.

**Comment by brandonnodnarb** [comment]
Hey @lewismc --- I did *not* do the bulk of the work manually.  I did edit the underscores manually as there were only about 20 so I used it as an opportunity to spot check (hence the extra commits). 

Happy to discuss.  It should be good to go.  There are a load of related issues, most of them already logged.  As you say, I think it's a good start.  Hopefully the session at the ESIP summer meeting can enhance what was added programmatically.  (I also have a little over 2000 candidate concept/term definitions, but I wanted to see how this was received before I open that can of worms :)  )

I believe @nsjuty was also at PIDapalooza in Dublin, but I did not introduce myself.

**Comment by rduerr** [comment]
Hey Brandon, are any of those definitions cryo-related?  If so, we should get together as I've been doing work with the Global Cryosphere Watch glossaries, so should make sure they are fairly consistent.

**Comment by brandonnodnarb** [comment]
Many thanks, @dr-shorthair.  

@rduerr, I'll have a look and elaborate in the Issue #20 thread.

@lewismc, what's the protocol / etiquette for merging; am I ok to merge my own commit, or should someone else?
You also mentioned you'd like to discuss further. Is that still the case?

**Comment by cmungall** [comment]
This is great! One less hack in our ENVO-SWEET alignment pipeline!

**Pull request merged**
