### PR TITLE
fixes #76 for stateTime.ttl

### LINKED ISSUE #76: Malformed subject URIs for owl:NameIndividuals that begin with a numeric
**what is wrong**
The owl:NamedIndividual URIs for terms that start with a numeric value (seen in the comment preceding the defining triples) is missing the numeric value in the defining triples

**Example**
<pre>
###  http://sweetontology.net/stateTime/1day
stime:day rdf:type owl:NamedIndividual ,
                   time:Duration ;
          screla:hasUnit units:day ;
          screla:hasNumericValue "1.0"^^xsd:double .
</pre>
Should this be:
<pre>
###  http://sweetontology.net/stateTime/1day
stime:1day rdf:type owl:NamedIndividual ,
                   time:Duration ;
          screla:hasUnit units:day ;
          screla:hasNumericValue "1.0"^^xsd:double .
</pre>

**Code Affected**
https://github.com/ESIPFed/sweet/blob/a59aaa1dc5833d88b2dd4eec65b0dc1f2358c2f0/src/stateTime.ttl#L212-L290

### PR DESCRIPTION
**Pull request by ashepherd**

### CODE REVIEW

**Comment by lewismc** [comment]
+1 from me... @carueda we need to investigate how this information was somehow lost in the translation or formatting process.

**Comment by ashepherd** [comment]
fixes #76 for stateTimeGeologic.ttl owl:NamedIndividual statements starting with a numeric

**Comment by carueda** [comment]
@lewismc yes, see https://github.com/ESIPFed/sweet/issues/76#issuecomment-356064535

@ashepherd Adam, can you confirm these ontologies continue to be valid? I have this vague recollection about leading numeric characters rendering the local part of a URI invalid, but I might be wrong.

**Comment by ashepherd** [comment]
hey @carlos, I think URIs that start with numerics are ok. I just inserted some test RDF into Virtuoso with a subject URI of `test:123uri`. But, I'm not an expert!

**Comment by carueda** [comment]
Cool, thanks much @ashepherd !

**Comment by dr-shorthair** [comment]
A URI in which the final element starts with a number is a valid URI, but cannot be contracted as a QName because XML Name can only start with alpha or underscore [1]. 
The CURIE specification overcomes this in principle (see paras 3-5 in [2]), but some environments still like QNames. 

[1]  https://www.w3.org/TR/REC-xml/#NT-NameStartChar
[2] https://www.w3.org/TR/2010/NOTE-curie-20101216/#s_intro

**Comment by carueda** [comment]
So, @dr-shorthair do you think QNames are somehow being involved during OWLAPI's processing thus causing the "misbehavior"?

**Comment by dr-shorthair** [comment]
Dunno, but TopBraid (which does not use OWLAPI) also stumbles on this.

**Comment by lewismc** [comment]
I think a diff is required here as right now, the extent of information we have lost from an unknown number of URI's is not currently known...

**Comment by graybeal** [comment]
perhaps a regex search is sufficient (all the names starting with a number in the 2.3 version)?

**Comment by xgmachina** [comment]
Following #76 and come to here. I saw another issue in https://github.com/ESIPFed/sweet/blob/master/src/stateTimeGeologic.ttl 
For a named instant (time boundary), there better be a unit for it, i.e. MYA / million years. @dr-shorthair , is there a unit for MYA in owlt or other ontologies?

**Comment by dr-shorthair** [comment]
I presume you mean the timescale (temporal coordinate reference system, with a datum, direction and scale) not the unit-of-measure (which only measures the duration of a time interval) which is a very different thing. 

In principle, this one should work 
http://www.opengis.net/def/crs/OGC/0/ChronometricGeologicTime 
but is currently throwing an exception - I'm following up. 
(It is mentioned in the OWL-Time rec)

Also http://resource.geosciml.org/classifier/cgi/geologicage/ma

**Comment by xgmachina** [comment]
Thanks, @dr-shorthair. I was recalling previous works when I was reusing the vocabularies you built. 
For Example: http://resource.geosciml.org/vocabulary/timescale/isc2012.ttl 
isc:BaseMiddleJurassicTime
      rdf:type tm:Coordinate ;
      tm:frame <http://resource.geosciml.org/classifier/cgi/geologicage/ma> ;
      tm:value "174.1"^^xsd:float ;
      thors:positionalUncertainty
              isc:BaseMiddleJurassicUncertainty .

So, yes we need a time scale frame to show the meaning of the value is about million years.

**Pull request merged**
