### PR TITLE
corrected spelling of noctilucent cloud

### PR DESCRIPTION
**Pull request by brandonnodnarb**
NOTE: did not change URI

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @brandonnodnarb see my comment on the `Pyroxene` issue.

**Comment by brandonnodnarb** [comment]
Hmmm...  I had a look.  Apologies, the first go round on issue #128 I was focused on the `deprecation' aspects.  

Was the deprecation because the IRI slug doesn't match the class label?  Aren't the IRIs arbitrary?  Which is to say they can be treated as arbitrary now that they are not a proxy for the class label _as well_. 

I can deprecate the classes and create new ones.  I just want to make sure I understand the rationale...mostly so I don't munt anything...

Also applies to #213.

**Comment by brandonnodnarb** [comment]
Thank you for your replies @graybeal.   I can't say I agree; I don't currently believe non-opaque IRIs to be fundamental (to SWEET or otherwise) or that opaque IRIs are a problem --- or that SWEET need to have only one type for that matter.

However, the replies suggest continuing with non-opaque IRIs --- at least until such time that issue #49 is resolved.   That's what I was asking for confirmation on.

**Comment by brandonnodnarb** [comment]
Updated.

**Review by dr-shorthair — APPROVED** [review]

**Comment by lewismc** [comment]
@graybeal can you please review ? Thanks

**Review by graybeal — APPROVED** [review]
looks good. I'm not sure what we decided about a 'replacedBy' property (I thought we agreed to have one, but not sure)—seeAlso is not very precise, especially for an automated tool to assess. But I think it should be merged and fixed later if need be.

**Pull request merged**
