### PR TITLE
ISSUE-126 SWEET-SSN mappings with individual detail/provenance

### PR DESCRIPTION
**Pull request by dr-shorthair**
Responding to #126

### CODE REVIEW

**Comment by lewismc** [comment]
@dr-shorthair it looks like there is a fair bit of overlap between this and #127 can you rebase ?

**Comment by dr-shorthair** [comment]
OK - I think it is clean now (when you review diffs suggest you suppress whitespace changes though ...)

**Comment by lewismc** [comment]
We need to extend [watchdog](https://github.com/ESIPFed/sweet-tools/tree/master/sc/watchdog) to accommodate changes to `alignments` directory as well such that these alignments are also included in the underlying graph.

**Comment by dr-shorthair** [comment]
What does `watchdog` accomplish?

**Comment by graybeal** [comment]
I believe it's the tool that watches for changes in certain ontologies (CF, SWEET), updating any that have changed.  (Even if that's right, it may have other elements too.)

**Comment by lewismc** [comment]
Correct John, it makes sure that commits to [./src](https://github.com/ESIPFed/sweet/tree/master/src) on master branch are reflected automatically into COR and subsequently served as linked data.

**Comment by dr-shorthair** [comment]
So we need to be clear whether or not they _should_ be reflected in the COR version. 
They are managed in a separate graph for a couple of reasons - 
(a) different provenance and governance
(b) so that a user can choose whether or not they trust them, find them useful, and want to load them 

If they automatically get added to COR, then I think we are asserting that, as far as ESIP is concerned, they are 'authoritative'. 

(I don't see any risks with these ones, but we must be clear about the precedent here.)

**Pull request merged**
