### PR TITLE
ISSUE-27 - SWEET-SOSA/SSN alignment axioms in a single graph

### PR DESCRIPTION
**Pull request by dr-shorthair**
I moved the smattering of alignment axioms out of the SWEET files and into a single mapping graph. 
This PR addresses #27 and replaces #41

### CODE REVIEW

**Comment by carueda** [comment]
@dr-shorthair I only see a new file in this PR. So, where are the modified SWEET files?

BTW, as a way of basic verification, I just loaded `sweet-ssn-mapping.ttl` into Protégé (v5.2.0, the latest which I just downloaded) and it seems to be "mostly" happy: the log shows quite a few warnings and errors, but they seem related with imported ontologies not with `sweet-ssn-mapping.ttl` itself; I'll take a closer look later and perhaps enter a new issue.

**Comment by dr-shorthair** [comment]
I did a brute-force rebase - copied the alignment axioms into a single file in new branch, so didn't need to modify any SWEET files.

**Comment by carueda** [comment]
OK.

Hmm, it's not clear how to enter a new review with "approved" ... anyway, consider this comment to have that effect. Thx.

**Comment by carueda** [comment]
@lewismc Keeping alignments in separate repos sounds fine to me.

**Comment by graybeal** [comment]
I'm OK with alignments in a separate folder.  I'm curious though, what was the motivation for storing alignments in a separate repository, as opposed to a separate folder in the SWEET repository? Both solutions seem equally modular, and there doesn't seem to be any concern about confusing the alignments with the core vocabulary in either case. The only disadvantage I see is that if you align with a number of ontologies, you will end up with a noticeably bigger repository (but not orders of magnitude).

**Comment by dr-shorthair** [comment]
+1 to @graybeal

**Comment by lewismc** [comment]
ACK @graybeal I went ahead and merged this issue then made a quick commit to move this initial alignment into an ```alignments``` subdirectory

**Pull request merged**
