### PR TITLE
ISSUE-107 sosa:sample vs sosa:sampling issue

### PR DESCRIPTION
**Pull request by lewismc**
Simply formalized the PR for #107 
Work done by @dr-shorthair

### CODE REVIEW

**Comment by lewismc** [comment]
@charlesvardeman can you review. Also, @rduerr can you have a look?

**Comment by charlesvardeman** [comment]
This looks like a good way to solve the issue and reviewed the changes. We will have to discuss whether some upper parent classes will be necessary to ground the process concept.

**Comment by dr-shorthair** [comment]
I've disentangled the mapping-provenance-reification material from the sweet-ssn mapping and moved that to a separate issue/branch

**Comment by dr-shorthair** [comment]
Thanks @rduerr 

1. I just added comments to Sample and Sampling, giving a narrative definition of each (short)
2. Is this module (reprSciModel) the correct place for these concepts?

**Comment by rduerr** [comment]
@dr-shorthair 

1. Definitions look ok to me.

2.  I don’t think there is any other place in SWEET that they could go!

**Pull request merged**
