### PR TITLE
Proposed class for generic act-of-observation

### LINKED ISSUE #149: Act of Observation
## Preferred term label
Observation

## Synonyms
Observing process

## Textual definition
Act to generate an estimate of the value of a property of a thing in the world. 

Implements a procedure at a known time; generates a piece of information

bco:ObservingProcess (from OBO) is a sub-class.
`res:Observation` is a sub-class.

See https://www.w3.org/TR/vocab-ssn/#SOSAObservation

## Suggested parent term
Likely belongs in reprSciModel module, `mod:Observation`
Probably `rdfs:subClassOf proc:Process`

## Attribution
https://orcid.org/0000-0002-3884-3420

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #149

### CODE REVIEW

**Review by brandonnodnarb — APPROVED** [review]
+1.
The comments provide a useful definition and further commentary for future development .

**Review by graybeal — APPROVED** [review]
This is nice to have. A question about the lines:
> bco:ObservingProcess (from OBO) is a sub-class.
> sohur:Observation (SWEET) is a sub-class.

does this imply we would always or often announce in plain text the inverse of the sub-class relations, that is, we'd always put in the superclass "blah-blah is a sub-class" ?  If not what is the guidance for when to do this?  It's really handy knowledge in this case, I just wonder if it's sustainable.

**Comment by dr-shorthair** [comment]
I added those comments to indicate that I had analysed SWEET to figure out how the proposed class fitted in to what was already there. It is annotation, and therefore optional (and probably not scalable).

**Review by smrgeoinfo — APPROVED** [review]
a useful addition

**Pull request merged**
