### PR TITLE
ISSUE-122 removed org.semanticweb.owlapi/error links from ttl files

### PR DESCRIPTION
**Pull request by brandonnodnarb**
I removed the http://org.semanticweb.owlapi/error#Error(n) links which were in place of (at least some) cardinality restrictions.

I'm not sure this addresses the 403 error being issued by Protege and the older version of TopBraid.  I would think http://org.semanticweb.owlapi/error#Error(n) URIs would return a different error code.  

Regardless, it was an error and is now resolved.  Need to test to see if it resolves the current web url load issue.  

Possibly of note, following @dr-shorthair's findings, when testing TopBraid 6.2 (free version) it loaded at least some of the files, but had the http://org.semanticweb.owlapi/error#Error(n) URIs as class names.  So, it didn't throw an error, but I'm not convinced it loaded everything properly (at least on my machine).

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @brandonnodnarb do you have any idea how all of the garbage ended up in here? I'm surprised we didn't catch this earlier but yet again we have limited review capabilities. 
We need to start working on some sort of CI solution which runs upon submission of every pull request. I think we should discuss at this weeks meeting - https://sched.co/PtTi

**Comment by lewismc** [comment]
OK, it looks like the _Error_ Classes were introduced in [this commit](https://github.com/ESIPFed/sweet/commit/15dc96fd70b537de925e3a17831a829f79351cf0#diff-935644dc67ccbc13054054826bd374ea)... that's OK as it is now getting fixed. Having reviewed the PR personally, I'm surprised I didn't pick any of these glaring obvious discrepancies up at the time. This is disappointing.

**Comment by brandonnodnarb** [comment]
Hi @lewismc, most of the stuff I deleted was actually fairly inconsequential, or there because the cardinality restrictions either weren't recognised, or the URIs referenced were ...unreferenceable.   The class assertions are for convenience and I think only used when the file with referenced class is not present.  I only deleted for convenience while comparing to previous version.

However, the fact that these were all cardinality restrictions is troubling and unlikely to be a coincidence.  I'm not yet sure what happened there.  I did notice that the OWLAPI version was inconsistent.  If you look at the [footer in any of the files from the last pull request (ISSUE-20)](https://github.com/ESIPFed/sweet/commit/15dc96fd70b537de925e3a17831a829f79351cf0#diff-a56cf742c3f33669cfd01965e1b9dc01) you should find the following two lines:
`Generated by the OWL API (version 5.1.2.2017-10-13T07:13:07Z) https://github.com/owlcs/owlapi/
Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi`

The first line overwritten by the second.  I don't know how backward compatible the OWLAPI is, but being a full version behind may cause some issues.  It's unclear if that had any ramifications for **this particular** issue, but I would expect that to be the cause of something either current or in the future.  

As #20 was the last issued pull request for most of these files, and I'm the one who did that work and issued that pull request, I should mention that I don't see how that work would have caused this error.  

(The rest is me explaining the process of adding labels)

I pulled (well, copied) all the commented URIs from each file and then split out each entity in the URI ---thee base, file/realm, and class name (CamelCase).  I then split all the words based on the uppercase letters, and then converted the string to lowercase (after the duscussion).  I then appended a statement to end of each file for each URI I found.  So, for the turtle file [realmHydro.ttl](https://github.com/ESIPFed/sweet/blob/master/src/realmHydro.ttl) I added all statements starting with 'hydr:' (as that is the prefix) to the end of the file, just above the OWLAPI footer.  For example, these are the first four statements added to realmHydro.ttl (because they are the first four classes in that file):
`hydr:Aquiclude rdfs:label "aquiclude"@en .`
`hydr:Aquifer rdfs:label "aquifer"@en .`
`hydr:Aquifuge rdfs:label "aquifuge"@en .`
`hydr:Aquitard rdfs:label "aquitard"@en .`

After all the statements were added to each file I loaded the edited local copy of SWEET into Protege 5.5 and saved it so the OWLAPI would re-write the file such that all the statements were organised with thier associated classes and not random statements all over the show. 

I mention this because I do not see how that series of events would wank cardinality restrictions.  Using an OWLAPI almost a full version behind...maybe.  

I agree there are a host of things up for discussion and the meeting is a great place to do that.  I'll ping you separately about this.  (Apologies all for the length of this comment.)

**Comment by carueda** [comment]
Regarding this diff:

```
Generated by the OWL API (version 5.1.2.2017-10-13T07:13:07Z) https://github.com/owlcs/owlapi/ 
Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi
```

I find this OWLAPI versioning very peculiar: presumably "older" version 4.5.9 is associated with a pretty recent timestamp `2019-02-01`, whereas (presumably newer) version `5.1.2` with `2017`!

**Comment by lewismc** [comment]
@carueda owlapi v4 and v5 are maintained as separate software products. We should either use one or the other (I suggest v5.X) and then stick to it.

**Comment by lewismc** [comment]
@brandonnodnarb 

> ...After all the statements were added to each file I loaded the edited local copy of SWEET into Protege 5.5 and saved it

I think this is the issue. I've seen discrepancies like this occur when developing the [sweet-snn-mapping](https://github.com/ESIPFed/sweet/blob/master/alignments/sweet-ssn-mapping.ttl)

**Comment by brandonnodnarb** [comment]
Thanks both @carueda and @lewismc for checking.  I'll push now and test in the morning.

**Pull request merged**
