### PR TITLE
Resolve #63 - Replace all default (no-prefix) namespaces with standardized prefixes

### LINKED ISSUE #63: Remove all remaining 'default' namespaces
A small number of 'default' (i.e. no prefix) namespaces remain. 
These associate different namespaces (URI stems) with 'no prefix' depending on which file is currently in focus. It is probably best to use namespace prefixes consistently across SWEET, so I suggest cleaning these up. 

I will prepare a PR. 

Follow-on from #48, #58

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fix for #63

### CODE REVIEW

**Comment by dr-shorthair** [comment]
I reverted the last commit, so this pull request is only concerned with ensuring there are no no-prefix namespaces.

**Comment by dr-shorthair** [comment]
@lewismc can you confirm protocol for accepting PRs and merging. 
If the submitter is also one of the editors, can they do the merge if the reviews come in +ve. 
Else should it always be different editor? 

For example, I think this one is uncontentious, but I had assigned it to you for probity's sake.

**Comment by carueda** [comment]
@lewismc @dr-shorthair 
I think it's in general desirable that the person merging the PR be different than the person that submitted it.

**Comment by lewismc** [comment]
@dr-shorthair  as we continue to the grow the community here hopefully more folks will be in a position to review and merge. +1 to @carueda suggestion

**Comment by lewismc** [comment]
@carueda is this PR superseded by #66 ?

**Comment by carueda** [comment]
@lewismc @dr-shorthair 
No. This one changes only 9 files. I think this one should be merged first. Then, I can update https://github.com/ESIPFed/sweet/pull/66 if needed and let you both know.

**Pull request merged**
